# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='start_rating',
            new_name='star_rating',
        ),
    ]
