# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20171112_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Guest')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking_Status',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='country_code',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.DeleteModel(
            name='Country_Code',
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Room'),
        ),
    ]
