# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20171112_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='hotel', chained_model_field='hotel', on_delete=django.db.models.deletion.CASCADE, to='booking.Room'),
        ),
        migrations.AlterField(
            model_name='room_type',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room_type',
            name='room_standard',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room_type',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('twin', 'Twin'), ('triple', 'Triple'), ('multiple', 'Multiple')], max_length=10),
        ),
    ]
