# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20171117_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='hotel_id',
            new_name='hotel',
        ),
    ]
