# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20171117_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Hotel')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Room')),
            ],
        ),
    ]
