# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20171208_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='avatar',
            field=models.ImageField(default=1, upload_to='media/images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='avatar',
            field=models.ImageField(default=1, upload_to='media/images'),
            preserve_default=False,
        ),
    ]
