# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20171213_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media/images'),
        ),
    ]
