# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 00:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20171213_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.IntegerField(default=67, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
