# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 04:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20171213_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='user',
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
