# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0020_auto_20171213_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
