# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 05:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0021_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='guest',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
