# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 10:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_auto_20171214_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='rate',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
