# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0028_rating_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='hotel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='booking.Hotel'),
        ),
    ]
